# CI to recreate and submit an AML pipeline when the code changes

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'
  inputs:
    versionSpec: '3.6'

- task: AzureCLI@1
  displayName: 'Install Azure ML CLI Extension'
  inputs:
    azureSubscription: 'ca-dabrady-demo-test (bc202ec2-54ef-4576-b7fb-a961c983398e)'
    scriptLocation: inlineScript
    inlineScript: 'az extension add -n azure-cli-ml'

- script: 'pip install --upgrade azureml-sdk'
  displayName: 'Install AzureML'

- task: AzureCLI@1
  displayName: 'Recreate and submit pipeline'
  inputs:
    azureSubscription: 'ca-dabrady-demo-test (bc202ec2-54ef-4576-b7fb-a961c983398e)'
    scriptLocation: inlineScript
    inlineScript: |
      echo 'running python script:'
      python $(Build.Repository.LocalPath)/setup_pipeline.py -d $(datastorename) -p $(datastorepath) -c $(computetarget)
